from .login_form import LoginForm
from .signup_form import SignUpForm
from .workspace_form import WorkSpaceForm
from .edit_workspace_form import EditWorkSpaceForm
from .task_form import TaskForm
from .edit_task_form import EditTaskForm
from .edit_task_form import EditTaskDateForm
from .category_form import CategoryForm
from .edit_category_form import EditCategoryForm
from .friend_form import FriendRequestForm
