"""empty message

Revision ID: 069e061ec513
Revises: f8c56d90319b
Create Date: 2022-02-21 09:45:04.278473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069e061ec513'
down_revision = 'f8c56d90319b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.String(length=70), nullable=True))
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
