"""empty message

Revision ID: 35086ba60d80
Revises: 069e061ec513
Create Date: 2022-03-14 18:11:42.670136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35086ba60d80'
down_revision = '069e061ec513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendRequests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendsList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend1_id', sa.Integer(), nullable=False),
    sa.Column('friend2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friend2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendsList')
    op.drop_table('friendRequests')
    # ### end Alembic commands ###
